# Generated by Django 4.1.3 on 2022-11-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='carrito',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='compras',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='compras',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
