# Generated by Django 4.1.3 on 2022-11-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_producto_id_carrito_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='estado',
            field=models.BooleanField(),
        ),
    ]
